package ru.adonixis.biometricassist.face

enum class FaceHint {
    NO_FACES_DETECTED,
    MULTIPLE_FACES_DETECTED,
    RAISE_HEAD,
    LOWER_HEAD,
    TURN_HEAD_LEFT,
    TURN_HEAD_RIGHT,
    ROTATE_HEAD_CLOCKWISE,
    ROTATE_HEAD_COUNTERCLOCKWISE,
    MOVE_PHONE_CLOSER,
    MOVE_PHONE_FARTHER,
    FACE_FULLY_IN_FRAME,
    FACE_NOT_OBSTRUCTED,
    NEUTRAL_EXPRESSION_REQUIRED,
    OPEN_EYES,
    IMPROVE_ILLUMINATION,
    REDUCE_DISTORTION
}
